### ISSUE TITLE
change "returnkey" to be something else - not featured??

### ISSUE THREAD

**Issue by fkkcloud** [driftyco/ionic-plugin-keyboard#126] opened 2015-09-04 16:21 UTC
I want to change my return key to be "Send" from "Go" or "Return",

I know that iOS has this feature options,
typedef enum {
    UIReturnKeyDefault,
    UIReturnKeyGo,
    UIReturnKeyGoogle,
    UIReturnKeyJoin,
    UIReturnKeyNext,
    UIReturnKeyRoute,
    UIReturnKeySearch,
    UIReturnKeySend,
    UIReturnKeyYahoo,
    UIReturnKeyDone,
    UIReturnKeyEmergencyCall,
} UIReturnKeyType;

What about ionic-plugin-keyboard? Where can I find it?

**Comment by tlancina** [comment] 2015-09-14 22:15
Hey, this is a pretty common request: https://github.com/driftyco/ionic-plugin-keyboard/issues/54, https://github.com/driftyco/ionic-plugin-keyboard/issues/20, https://github.com/driftyco/ionic-plugin-keyboard/issues/9.

Closing as a duplicate of https://github.com/driftyco/ionic-plugin-keyboard/issues/54.

**Closed by tlancina** 2015-09-14 22:15 UTC
