### ISSUE TITLE
Focus on input conflicts with disableScroll

### ISSUE THREAD

**Issue by dangnelson** [driftyco/ionic-plugin-keyboard#111] opened 2015-07-06 18:04 UTC
Is there a supported / tested directive for input auto-focus that works with this plugin?

I'm using it in an Ionic project using ngCordova and am having it over-ride my disableScroll command.

See a related forum here:
http://forum.ionicframework.com/t/auto-focus-textbox-while-template-loads/6851

**Comment by vladshirochenko** [comment] 2015-07-10 08:22
Read the docs http://cordova.apache.org/docs/en/5.0.0/guide_platforms_ios_config.md.html#iOS%20Configuration

KeyboardDisplayRequiresUserAction (boolean, defaults to true): Set to false to allow the keyboard to appear when calling focus() on form inputs.

<preference name="KeyboardDisplayRequiresUserAction" value="false"/>

**Comment by dangnelson** [comment] 2015-07-10 13:38
I did that, but have been having issues with calling focus interfering with the plugin. Specifically, it's been over-riding disableScroll on an iOS Ionic project. 

disableScroll works great UNTIL I add focusMe, at which point it breaks.

Here's my code, pretty straight forward:

Controller in controllers.js :

    .controller('LoginPhoneCtrl', function($scope,  $cordovaKeyboard, $ionicPlatform, $window) {
	   $ionicPlatform.ready(function() {
		 if ($window.cordova) {
		   $cordovaKeyboard.disableScroll(true);
		   $cordovaKeyboard.hideAccessoryBar(false);
          }
       });
    })

Config.xml

    <preference name="KeyboardDisplayRequiresUserAction" value="false"/>

Focus Directive in App.js

    .directive('focusMe', function($timeout) {
      return {
        link: function(scope, element, attrs) {
          $timeout(function() {
            element[0].focus(); 
          },750);
       }
     };
    });

Example Input

     <input type="text" class="form-control" id="firstname" name="firstname" ng-model="firstname" placeholder="First Name (required)"  autocorrect="off"  focus-me />

**Comment by tlancina** [comment] 2015-08-26 00:05
Is this only on the simulator or on a device as well? If someone could post a minimal test case with steps to reproduce I'll take a look, thanks!

**Comment by dangnelson** [comment] 2015-08-26 01:25
Here are the steps to recreate this problem:

Start with a basic ionic project.
Have your first page be a long form. like so:

    <ion-view view-title="Dashboard">
    <ion-content class="padding">
  	<form>
	    <div class="list">
			<label class="item item-input">
				<span class="input-label">Form Input</span>
				<input type="text" focus-me>
			</label>
			<label class="item item-input">
				<span class="input-label">Form Input</span>
				<input type="text">
			</label>
			<label class="item item-input">
				<span class="input-label">Form Input</span>
				<input type="text">
			</label>
			<label class="item item-input">
				<span class="input-label">Form Input</span>
				<input type="text">
			</label>
			<label class="item item-input">
				<span class="input-label">Form Input</span>
				<input type="text">
			</label>
			<label class="item item-input">
				<span class="input-label">Form Input</span>
				<input type="text">
			</label>
			<label class="item item-input">
				<span class="input-label">Form Input</span>
				<input type="text">
			</label>
			<label class="item item-input">
				<span class="input-label">Form Input</span>
				<input type="text">
			</label>
			<label class="item item-input">
				<span class="input-label">Form Input</span>
				<input type="text">
			</label>
			<label class="item item-input">
				<span class="input-label">Form Input</span>
				<input type="text">
			</label>
		</div>
  	</form>
    </ion-content>
    </ion-view>

Install the ionic keyboard.

In app.js enable the keyboard accessory bar:

    cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false);

Add an auto-focus directive as suggested here: 
http://forum.ionicframework.com/t/auto-focus-textbox-while-template-loads/6851/9

    .directive('focusMe', function($timeout) {
      return {
       link: function(scope, element, attrs) {
		console.log("focus");
         $timeout(function() {
           element[0].focus(); 
         },750);
       }
       };
    });

Activate auto focus by adding focus-me to a form field.

And add these to the config.xml file 

    <preference name="KeyboardDisplayRequiresUserAction" value="false" />
  
    <feature name="Keyboard">
      <param name="ios-package" value="IonicKeyboard" onload="true" />
    </feature>

That's the only way I've gotten auto-focusing to work, but it breaks disableScroll every single time.

**Comment by tlancina** [comment] 2015-09-15 02:02
@dangnelson thanks for the test case! Apologies for the super delay, we are a fairly small team and are in the midst of some pretty big stuff right now :) I actually couldn't reproduce the issue at first, but if I remove the timeout delay it messes up the scroll view every time for me.

This is a tricky one.  If you wrap the focus in an `ionic.Platform.ready()` instead of an arbitrary timeout you've guaranteed that all the plugins are loaded and the Cordova native side is ready to receive your commands.  The problem is, it looks like the queue of commands (including cordova.plugins.Keyboard.disableScroll) won't be consumed by the native side until the next event loop, so your focus happens before disableScroll has actually been set.

To get around this you can wrap your focus call in an additional timeout:
```
ionic.Platform.ready(function() {
    $timeout(function(){ element[0].focus() }); 
});
```
 or you could edit the plugin file to have disableScroll default to `YES` on the initial load.

This fixes the disableScroll issue.  The next issue is that the ionic keyboard code won't initialize until the first touch event (there are no keyboards on desktop, so we don't want to completely mess up the layout of people testing on desktop).  So you can manually poke the keyboard into initializing before you call focus:
  ```
if (firstTime) {
    ionic.keyboard.enable();
    firstTime = false;
}
ionic.Platform.ready(function() {
    $timeout(function(){ element[0].focus(); }) 
},750);
```

Closing this as there's not much to be done from the plugin side of things, but feel free to post back if you're still having issues.

**Closed by tlancina** 2015-09-15 02:02 UTC

**Comment by dangnelson** [comment] 2015-09-17 16:56
Your code will only work on the initial launch due to the ionic.Platform.ready wrapper.

It needs to work whenever the view is shown, not just on initial launch.

Can you also show the complete code for the directive? I was unable to make this work using the provided code.

This is a plugin specific issue, and being able to have auto focusing work is expected usage. Providing an official work around in the documentation would be good practice to say the least...

**Comment by tlancina** [comment] 2015-09-17 19:00
Hey @dangnelson, the code only works on initial launch because views are cached in Ionic for performance reasons, so your directive only fires once.  You can read up on view caching here: http://ionicframework.com/docs/api/directive/ionNavView/. The ionic.Platform.ready function waits to fire its callback until the 'deviceready' event has fired, if 'deviceready' has already fired it executes the callback immediately (and will do so for subsequent calls as well, it doesn't work like _.once)

If you want it to re-fire every time you load a new view you can do something like this to disable caching:
```
.config(function($ionicConfigProvider){
  $ionicConfigProvider.views.maxCache(0);
})
```

I agree that there is a plugin specific issue here, namely that you should be able to configure the plugin defaults before runtime without having to edit the source file.  I have opened a new issue for using config.xml to set disableScroll to 'YES' or 'NO' from a config.xml preference: https://github.com/driftyco/ionic-plugin-keyboard/issues/130

Here is the full directive for you:
```
.config(function($ionicConfigProvider){
  $ionicConfigProvider.views.maxCache(0);
})

.directive('focusMe', function($timeout) {
  var firstTime = true;
  return {
    link: function(scope, element, attrs) {
      if (firstTime) {
        ionic.Platform.ready(function() {
          ionic.keyboard.enable();
          //wait for view to transition for 300ms
          $timeout(function(){ element[0].focus(); }, 300, false) 
        });  
        firstTime = false;
      } else {
        $timeout(function(){ element[0].focus(); }, 300, false);
      }
    }
  }
})
```

Hope that helps!

**Comment by dudeveloper** [comment] 2016-08-03 12:09
Converted ion-content to an ion-scroll and it fixed the issue.
